### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by philmetzger** [JeffersonFilho/react-linkedin-sdk#1]
```
ReferenceError: window is not defined
    at C:\Projects\project\frontend\node_modules\react-linkedin-sdk\build\index.js:1:8983

```

Any idea how to resolve that?

```
<LinkedinSDK
                clientId="sdasdsadasdsads"
                callBack={this.responseLinkedin}
                fields=":(id,num-connections,picture-url)"
                className={'className'}
                textButton={'Login with Linkedin'}
                buttonType={'button'}
            />
```

**Comment by JeffersonFilho** [comment]
@philmetzger What browser/version are you using? I can't replicate the error.

**Comment by philmetzger** [comment]
Version 64.0.3282.167 (Official Build) (64-bit) on windows 10

**Comment by JeffersonFilho** [comment]
I see and what browser are you using? Are you using Reactjs on your NextJS app?

**Comment by philmetzger** [comment]
Sorry never specified, but google chrome (Version 64.0.3282.167 (Official Build) (64-bit) on windows 10).

Ya its a reactJs app

**Comment by JeffersonFilho** [comment]
if you're you using SSR(Server side rendering) you need to make sure ```window``` exist, because nodejs doesn't have it.

https://stackoverflow.com/questions/45964178/referenceerror-window-is-not-defined-at-object-anonymous-node-js

**Comment by philmetzger** [comment]
hmm but the issue originates in your package right? How can i check if windows exists

**Comment by JeffersonFilho** [comment]
Yes, because my package is using ```window``` and you can check if exists like this 
```
if(typeof window !== 'undefined') {
  console.log("this should print only if window object actually exists")
}
```

**Comment by DavyBello** [comment]
For anyone else using Next.js they have a helper you can use to get around this
check out
https://github.com/zeit/next.js#3-with-no-ssr
