### ISSUE TITLE
LinkedIn nam

### ISSUE THREAD

**Issue by rahilahmad** [JeffersonFilho/react-linkedin-sdk#10]
How am i able to fetch name of the current user? from this SDK

**Comment by JeffersonFilho** [comment]
You can check on the docs which field you want to get from the user: https://developer.linkedin.com/docs/fields/basic-profile

Example to how to fetch current user name:

```fields=":(id,first-name,last-name,num-connections,picture-url)"```

**Comment by Raheel1258** [comment]
Thanks man i have done this God bless you
