### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by SCasarotto** [JeffersonFilho/react-linkedin-sdk#11]
I just found this and wanted to test how it worked but every time I click on the linkedIn login button I receive this error in the popup: 

> 
> This site can’t be reached
> 
> The webpage at https://www.linkedin.com/uas/oauth/authorize?oauth_token=****************&state= might be temporarily down or it may have moved permanently to a new web address.
> 

Is the service down or did I implement things incorrectly?

**Comment by JeffersonFilho** [comment]
Seems to be working fine for me, could you please provide some code example?

**Comment by SCasarotto** [comment]
Odd it was a direct copy of your example code. 

Steps to recreate:
`npx create-react-app react-linkedin-sdk-test`
`cd react-linkedin-sdk-test`
`yarn add react-linkedin-sdk`
`yarn start`
Make App.js look like:
```
import React, { Component } from 'react'
import logo from './logo.svg'
import './App.css'
import LinkedinSDK from 'react-linkedin-sdk'

class App extends Component {
  responseLinkedin = (response) => {
    console.log(response)
  }
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <p>
            Edit <code>src/App.js</code> and save to reload.
          </p>
          <a
            className="App-link"
            href="https://reactjs.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            Learn React
          </a>
          <LinkedinSDK
            clientId="MY_KEY_HERE"
            callBack={this.responseLinkedin}
            fields=":(id,num-connections,picture-url)"
            // className={'className'}
            loginButtonText={'Login with Linkedin'}
            logoutButtonText={'Logout from Linkedin'}
            buttonType={'button'}
            // icon={<Icon />}
            getOAuthToken
          />
        </header>
      </div>
    )
  }
}

export default App
```
`yarn start`
Click button and get the following:
<img width="937" alt="screen shot 2018-10-23 at 4 44 00 pm" src="https://user-images.githubusercontent.com/13336976/47392697-f075b900-d6e2-11e8-96d1-302574f2e7ce.png">


So I guess it could be something with my key but I don't think I skipped any steps...

**Comment by JeffersonFilho** [comment]
The code looks all good, can you try to access ```https://www.linkedin.com/uas/oauth/authorize?oauth_token=&state=``` in your browser and see if you works?

**Comment by SCasarotto** [comment]
I land on this:

<img width="1140" alt="screen shot 2018-10-24 at 6 57 18 am" src="https://user-images.githubusercontent.com/13336976/47428860-2ace6d00-d75a-11e8-8b7a-7ec5ed7b5d59.png">

**Comment by JeffersonFilho** [comment]
Cool, could you also try on the normal chrome window? I'm just trying to narrow down the error, because looks like is your browser that can't make a connection with Linkedin but then as you showed on your picture on incognito you can access that page. 

Have you tried it in a different browser? Because if was a problem with the package you would at least be able to access the page and an error would've been displayed like it did when you tried to directly access it.

**Comment by SCasarotto** [comment]
Yeah sorry in the normal window the only difference is it has me logged in in the upper right. I have tried with a different browsers as well. Here is the link you provided on chrome and safari and the popup in safari after pressing the login button from this library.

Really appreciate you working through this with me.

<img width="830" alt="screen shot 2018-10-24 at 8 00 30 am" src="https://user-images.githubusercontent.com/13336976/47432160-1f337400-d763-11e8-8922-a9216e56f351.png">

**Comment by JeffersonFilho** [comment]
Okay so we now know that you can access that link on the normal browser.

Now could you try to copy the link from the popup with your token and paste on your browser and see if you can access it?

No worries, the pleasure is mine!

**Comment by SCasarotto** [comment]
Copying and pasting to a new window has the same result. Should there be a value after "state="?

**Comment by JeffersonFilho** [comment]
So we now confirmed that it's a problem with the url and it's normal to not have a value after "state" so the final test is to replace your token with a random string and see if you can access the page. If you can it's a problem with your token so then we can move forward to see what is causing this issue with your token.

**Comment by SCasarotto** [comment]
When I place a random string in I get this error in the console `You must specify a valid JavaScript API Domain as part of this key's configuration.`

I will try to review my token settings and see if I am missing anything.

**Comment by JeffersonFilho** [comment]
Did you added your domain on the Linkedin Application Settings > Javascript > Valid SDK Domains

**Comment by SCasarotto** [comment]
Yeah. Have you had any problems trying to run this on localhost?

**Comment by JeffersonFilho** [comment]
I just tested with the latest create-app and seems to be working just fine, is very weird this bug that you're having.
