### ISSUE TITLE
LinkedIn SDK EOL March 1, 2019

### ISSUE THREAD

**Issue by jcope2013** [JeffersonFilho/react-linkedin-sdk#14]
"SDKs: Our JavaScript and Mobile Software Development Kits (SDKs) will stop working. Developers will need to migrate to using OAuth 2.0 directly from their apps. "

"To reiterate: all developers need to migrate their apps to our newest APIs and OAuth 2.0 by March 1, 2019."

https://engineering.linkedin.com/blog/2018/12/developer-program-updates

Will this effectively mean this library will no longer work?

**Comment by JeffersonFilho** [comment]
I will have a look, if anything I can migrate the library to use OAuth 2.0 to keep it working.
