### ISSUE TITLE
Closing LinkedIn popup window without logging in causes button to remain disabled

### ISSUE THREAD

**Issue by ChrisEllis007** [JeffersonFilho/react-linkedin-sdk#2]
1. Click the linkedin component button to open the LinkedIn login window
2. Click on the X to close the popup window without logging in
3. linkedin component button button remains disabled

**Comment by JeffersonFilho** [comment]
Thanks for reporting it! I will have a look at it soon as possible!

**Comment by JeffersonFilho** [comment]
It should be fixed now on v1.0.9!
