### ISSUE TITLE
Logout?

### ISSUE THREAD

**Issue by eytireyup** [JeffersonFilho/react-linkedin-sdk#3]
Hey,

I really like your component. But I can't logout with Linkedin with this. How can we achieve this? What I understand from my research is there is no way to logout Linkedin via REST api. 

Thanks.

**Comment by JeffersonFilho** [comment]
Hey!

Thank you very much! I'm glad you liked it! That's a very good question, I will check the docs and see if is possible and let you know.

**Comment by JeffersonFilho** [comment]
This functionalty is now available on 1.0.10, thanks for suggesting it!
